---
title: "issuewithalignment"
format: html
editor: visual
---

```{r}
source("setup.R")
# Load pos data
seq_pos <- read_xlsx("../shared_data/seq_HE/seq_pos.xlsx", 
                 col_names = TRUE) |> as.data.frame()
seq_pos$polarity <- "pos"
# load neg data
seq_neg <- read_xlsx("../shared_data/seq_HE/seq_neg.xlsx", 
                 col_names = TRUE) |> as.data.frame()
seq_neg$polarity <- "neg"
seq <- rbind(seq_pos, seq_neg)

seq$filename <- paste0(seq$`Data File`, ".mzML")
mse <- readMsExperiment(paste0("../example/HE_mzml/", seq$filename), 
                        seq)

sampleData(mse)
```

```{r}
## susbet to the first sample 
idx <- which(sampleData(mse)$sample_type == "sample")[1]

## here is the peak of interest 
chr <- chromatogram(mse[idx], rt = c(30, 80), mz = c(283.98- 0.03, 283.98 + 0.03))
chr
plot(chr)
```

```{r}
cwp <- CentWaveParam(peakwidth = c(4, 12), ppm = 20, integrate = 2,
                     snthresh = 7, noise = 100, extendLengthMSW = TRUE)
mse <- findChromPeaks(mse, cwp, msLevel = 1L, chunkSize = 2L)
chromatogram(mse[idx], rt = c(30, 80), mz = c(283.98- 0.02, 283.98 + 0.02)) |> 
  plot()

mnpp <- MergeNeighboringPeaksParam(expandRt = 6, expandMz = 0.0015,
                                   minProp = 0.75)
mse <- refineChromPeaks(mse, mnpp, chunkSize = 2L)

chromatogram(mse[idx], rt = c(30, 80), mz = c(283.98- 0.02, 283.98 + 0.02)) |> 
  plot()
```

```{r}
#' loading info from NAPS 
naps_info <- read_xlsx("../shared_data/NAPS_info.xlsx", 
                       .name_repair = "minimal") |>
    as.data.frame()


#' calculate m/z 
naps_info$mz_pos <- mass2mz(naps_info$`exact mass`, adduct = "[M+H]+")[, 1]

#' subset positive polarity
naps_pos <- mse[sampleData(mse)[, "Sample.Name"] == "NAPS" &
                sampleData(mse)[, "polarity"] == "pos"]

#' Match chromatographic peaks against NAPS
cpks <- chromPeaks(naps_pos)
naps_pos_match <- matchValues(cpks, naps_info, mzColname = c("mz", "mz_pos"),
                              MzParam(tolerance = 0, ppm = 10))
naps_pos_match <- naps_pos_match[whichQuery(naps_pos_match)]
md <- matchedData(naps_pos_match, c("mz", "rt", "maxo", "sample",
                                    "ppm_error", "target_Name")) |>
    as.data.frame()


pos_rt_matrix <- naps_rt_matrix(md, naps_info)
colnames(pos_rt_matrix) <- paste0("NAPS_POS_", seq_len(ncol(pos_rt_matrix)))

#' Define m/z for the expected ions of the NAPS
naps_info$mz_neg <- mass2mz(naps_info$`exact mass`, adduct = "[M+CHO2]-")[, 1]

#' Negative polarity
naps_neg <- mse[sampleData(mse)[, "Sample.Name"] == "NAPS" &
                sampleData(mse)[, "polarity"] == "neg"]
cpks <- chromPeaks(naps_neg)
naps_neg_match <- matchValues(cpks, naps_info, mzColname = c("mz", "mz_neg"),
                              MzParam(tolerance = 0, ppm = 10))
naps_neg_match <- naps_neg_match[whichQuery(naps_neg_match)]
md <- matchedData(naps_neg_match, c("mz", "rt", "maxo", "sample",
                                    "ppm_error", "target_Name")) |>
    as.data.frame()

neg_rt_matrix <- naps_rt_matrix(md, naps_info)
colnames(neg_rt_matrix) <- paste0("NAPS_NEG_", seq_len(ncol(neg_rt_matrix)))
matchedData(naps_neg_match, c("rt", "maxo", "sample", "target_Name"))

rt_matrix <- cbind(pos_rt_matrix, neg_rt_matrix)
```

```{r}
pgp <- PeakGroupsParam(
    minFraction = 0.75,
    extraPeaks = 50,
    span = 0.5,
    subset = which(sampleData(mse)$sample_type == "NAPS"),
    subsetAdjust = "average",
    peakGroupsMatrix = rt_matrix)
mse <- adjustRtime(mse, param = pgp)


plotAdjustedRtime(
    mse)

chromatogram(mse[idx], rt = c(30, 80), mz = c(283.98- 0.02, 283.98 + 0.02)) |> 
  plot()
```
